#!/bin/sh
let mem=5000
while [ 1 ]
do
    java "-Xmx"$mem"m" -version > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
        break
    fi
    let mem=$mem-100
    if [ $mem -lt 100 ]
    then
        # something went wrong with our test
        let mem=700
        break
    fi
done

echo $mem
