#!/bin/sh
if [ -d .git ]
then
	echo Enabling OntoVCS for this Git repository
	if grep -q "owl2merge" .git/info/attributes 2>/dev/null
	then
		echo "OntoVCS is already enabled for this Git repository"
	else
		echo "*.rdf	diff=owl2diff">>.git/info/attributes
		echo "*.ttl	diff=owl2diff">>.git/info/attributes
		echo "*.owl	diff=owl2diff">>.git/info/attributes
		echo "*.rdf	merge=owl2merge">>.git/info/attributes
		echo "*.ttl	merge=owl2merge">>.git/info/attributes
		echo "*.owl	merge=owl2merge">>.git/info/attributes
		git config diff.owl2diff.command "owl2diff.git.sh"
		git config merge.owl2merge.driver "owl2merge.git.sh %O %A %B %A"
		echo "OntoVCS is now enabled for *.owl, *.rdf and *.ttl files in this Git repository
"
	fi
elif [ -d .hg ]
then
	echo "Enabling OntoVCS for this Mercurial repository"
	if grep -q "owl2merge" .hg/hgrc 2>/dev/null
	then
		echo "OntoVCS is already enabled for this Mercurial repository"
	else
		cat "$( cd "$( dirname "$0" )" && pwd )/hgrc.sample">>.hg/hgrc
		echo "OntoVCS is now enabled for *.owl, *.rdf and *.ttl files in this Mercurial repository
"
	fi
else
	echo "Current directory is not a supported repository or is not a repository at all"
fi
